#server:
#  port: 8084
spring:
  application:
    name: TRANSACCION-MS
  mvc:
    throw-exception-if-no-handler-found: true

  data:
    mongodb:
      uri: mongodb://mongo:VLvbBYdfrMtSyFsDBKMkcLerUMBqczVe@junction.proxy.rlwy.net:48114/test

# Configuración de SpringDoc para OpenAPI y Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    url: /openapi.yaml

# configuracion de eureka
eureka:
  client:
    service-url:
      defaultZone: https://euraka-server-production.up.railway.app/eureka/
      #Descomentar la siguiente línea para trabajar localmente:
      #defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: false
    hostname: transaction-ms-production.up.railway.app
    # Descomentar la siguiente línea para trabajar localmente:
    #hostname: localhost
