server:
  port: 8084
spring:
  application:
    name: TRANSACCION-MS
  mvc:
    throw-exception-if-no-handler-found: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcamp

# Configuración de SpringDoc para OpenAPI y Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    url: /openapi.yaml

# configuracion de eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: false
    #hostname: customer-ms-production.up.railway.app
    # Descomentar la siguiente linea para trabajar localmente:
    hostname: localhost